export enum UserAction {
  GET_USERS = 'user/GET_USERS',
  GET_USERS_SUCCEED = 'user/GET_USERS_SUCCEED',
  GET_USER_DETAILS = 'user/GET_USER_DETAILS',
  GET_USER_DETAILS_SUCCEED = 'user/GET_USER_DETAILS_SUCCEED',
}
